name: Build Electron App

on:
  push:
    branches: [ main ] # Se déclenche quand vous poussez du code sur la branche 'main'

jobs:
  build:
    runs-on: windows-2022 # Use specific version to avoid migration issues

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Utilise une version stable de Node.js
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build web application
      run: npm run build

    - name: Build Electron app
      run: npx electron-builder --win

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ventes-GRSO-Installer
        path: |
          release/*.exe
          release/*.blockmap
          release/latest.yml